src/Entity/Message.php
<?php
// src/Entity/Message.php
namespace App\Entity;

class Message
{
    
    private string $firstName;
    private string $lastName;
    private string $email;
    private string $message;

    public function getFirstName()
    {
        return $this->firstName;
    }
    public function setFirstName($firstname)
    {
        $this->firstName = $firstname;
    }
    
    public function getLastName()
    {
        return $this->lastName;
    }
    public function setLastName($lastname)
    {
        $this->lastName = $lastname;
    }

    public function getEmail()
    {
        return $this->email;
    }
    public function setEmail($email)
    {
        $this->email = $email;
    }

    public function getMessage()
    {
        return $this->message;
    }
    public function setMessage($message)
    {
        $this->message = $message;
    }
}

src/Entity/Post.php
<?php
// src/Entity/Post.php
namespace App\Entity;

use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\PostRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]

class Post
{
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int $Id;

    #[ORM\column(type: "datetime")]
    private \DateTime $Date;
    
    #[ORM\Column(length: 255)]
    private string $Subject;

    #[ORM\Column(type: "text")]
    private string $Text;

    public function getId()
    {
        return $this->Id;
    }
    
    public function getDate()
    {
        return $this->Date;
    }
    public function setDate($Date)
    {
        $this->Date = $Date;
    }

    public function getSubject()
    {
        return $this->Subject;
    }
    public function setSubject($Subject)
    {
        $this->Subject = $Subject;
    }

    public function getText()
    {
        return $this->Text;
    }
    public function setText($Text)
    {
        $this->Text = $Text;
    }
}

src/Form/ContactType.php
<?php 

// src/Form/ContactType.php
namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use App\Entity\Message;

class ContactType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName')
            ->add('lastName')
            ->add('email')
            ->add('message')
        ;
    }
    
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Message::class,
        ]);
    }
}

src/Form/PostType.php
<?php 

// src/Form/PostType.php
namespace App\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use App\Entity\Post;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Id')
            ->add('Date')
            ->add('Subject')
            ->add('Text')
        ;
    }
    
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/ContactController.php
<?php
// src/Controller/ContactController.php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\ContactType;
use App\Entity\Message;

class ContactController extends AbstractController
{
    /**
     * @Route("/contact")
     */
    public function contact(Request $request)
    {
        $message = new Message();
        $form = $this->createForm(ContactType::class, $message);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            dump($message);
        }
        return $this->render('contact.html.twig', array(
            'form' => $form->createView(),
        ));
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Form\PostType;
use App\Entity\Post;

class PostController extends AbstractController
{
    /**
     * @Route("/post")
     */
    public function Post (Request $request)
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            dump($post);
        }
        return $this->render('index.html.twig', array(
            'form' => $form->createView(),
        ));
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/contact.html.twig
{# templates/contact.html.twig #}
<html>
    <head></head>
    <body>
        {{ form_start(form) }}
        {{ form_row(form.firstName) }}
        {{ form_row(form.lastName) }}
        {{ form_row(form.email) }}
        {{ form_row(form.message) }}
        <button type="submit" class="btn btn-primary">Envoyer</button>
        {{ form_end(form) }}
        
    </body>
</html>

templates/index.html.twig
{# templates/index.html.twig #}
<html>
    <head></head>
    <body>
        {{ form_start(form) }}
        {{ form_row(form.Id) }}
        {{ form_row(form.Date) }}
        {{ form_row(form.Subject) }}
        {{ form_row(form.Text) }}
        <button type="submit" class="btn btn-primary">Envoyer</button>
        {{ form_end(form) }}
        
    </body>
</html>

templates/post.html.twig
{# templates/post.html.twig #}
<html>
    <head></head>
    <body>
        {{ form_start(form) }}
        {{ form_row(form.id) }}
        {{ form_row(form.date) }}
        {{ form_row(form.subject) }}
        {{ form_row(form.text) }}
        <button type="submit" class="btn btn-primary">Envoyer</button>
        {{ form_end(form) }}
        
    </body>
</html>